import { Product } from '../types/products';

export const availableProducts: Product[] =
  // [
  //   {
  //     name: "сникерс",
  //     price: 500,
  //     count: 7,
  //     id: 1,
  //     weight: "40г.",
  //     image: "src/static/productsImages/snickers.webp",
  //   },
  //   {
  //     name: "баунти",
  //     price: 15,
  //     count: 15,
  //     id: 2,
  //     weight: "30г.",
  //     image: "src/static/productsImages/bounty.webp",
  //   },
  //   {
  //     name: "марс",
  //     price: 5,
  //     count: 23,
  //     id: 3,
  //     weight: "45г.",
  //     image: "src/static/productsImages/mars.webp",
  //   },
  //   {
  //     name: "твикс",
  //     price: 6,
  //     count: 2,
  //     id: 4,
  //     weight: "50г.",
  //     image: "src/static/productsImages/twix.webp",
  //   },
  //   {
  //     name: "буратино",
  //     price: 7,
  //     count: 0,
  //     id: 5,
  //     weight: "1л.",
  //     image: "src/static/productsImages/буратино.webp",
  //   },
  //   {
  //     name: "тархун",
  //     price: 8,
  //     count: 0,
  //     id: 6,
  //     weight: "0.5л.",
  //     image: "src/static/productsImages/тархун.webp",
  //   },
  //   {
  //     name: "газированная вода",
  //     price: 9,
  //     count: 0,
  //     id: 7,
  //     weight: "2л.",
  //     image: "src/static/productsImages/вода-газированная.webp",
  //   },
  //   {
  //     name: "вода без газа",
  //     price: 10,
  //     count: 0,
  //     id: 8,
  //     weight: "2л.",
  //     image: "src/static/productsImages/вода-без-газа.webp",
  //   },
  // ];

  [
    {
      name: 'сникерс',
      price: 500,
      count: 0,
      id: 1,
      weight: '40г.',
      image: './productsImages/snickers.webp',
    },
    {
      name: 'баунти',
      price: 15,
      count: 0,
      id: 2,
      weight: '30г.',
      image: './productsImages/bounty.webp',
    },
    {
      name: 'марс',
      price: 5,
      count: 0,
      id: 3,
      weight: '45г.',
      image: './productsImages/mars.webp',
    },
    {
      name: 'твикс',
      price: 6,
      count: 1,
      id: 4,
      weight: '50г.',
      image: './productsImages/twix.webp',
    },
    {
      name: 'буратино',
      price: 7,
      count: 0,
      id: 5,
      weight: '1л.',
      image: './productsImages/буратино.webp',
    },
    {
      name: 'тархун',
      price: 8,
      count: 0,
      id: 6,
      weight: '0.5л.',
      image: './productsImages/тархун.webp',
    },
    {
      name: 'газированная вода',
      price: 9,
      count: 0,
      id: 7,
      weight: '2л.',
      image: './productsImages/вода-газированная.webp',
    },
    {
      name: 'вода без газа',
      price: 10,
      count: 1,
      id: 8,
      weight: '2л.',
      image: './productsImages/вода-без-газа.webp',
    },
  ];
